name: school_watch_semeru
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^6.5.5
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  equatable: ^2.0.5
  formz: ^0.6.0
  fpdart: ^0.5.0
  image_picker: ^0.8.7+3
  dotted_border: ^2.0.0+3
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  flutter_map_dragmarker: ^4.1.2
  maps_toolkit: ^2.0.1
  flutter_map_location_marker: ^5.3.0
  flutter_map_line_editor: ^4.0.2
  dio: ^5.1.1
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.1.0
  json_annotation: ^4.8.0
  flutter_staggered_grid_view: ^0.6.2
  polylabel: ^1.0.1
  http_parser: ^4.0.2
  otp_text_field: ^1.1.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator: ^2.2.1
  riverpod_lint: ^1.3.1
  custom_lint:
  freezed: ^2.3.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/QuickSand-Regular.ttf
        - asset: assets/fonts/QuickSand-Bold.ttf
          weight: 700
